// Pure logic for recurring expense rules: scheduling, sync, and label formatting.

const WEEKDAY_INDEX  = { sun: 0, mon: 1, tue: 2, wed: 3, thu: 4, fri: 5, sat: 6 }
const WEEKDAY_LABELS = {
  sun: 'Sunday', mon: 'Monday', tue: 'Tuesday', wed: 'Wednesday',
  thu: 'Thursday', fri: 'Friday', sat: 'Saturday',
}

export function localDateString(date) {
  const y = date.getFullYear()
  const m = String(date.getMonth() + 1).padStart(2, '0')
  const d = String(date.getDate()).padStart(2, '0')
  return `${y}-${m}-${d}`
}

function parseLocalDate(dateStr) {
  const [y, m, d] = dateStr.split('-').map(Number)
  return new Date(y, m - 1, d)
}

// Returns "YYYY-MM-DD" for the target day in the given month.
// recurrenceValue: 'last' | number 1-31 (clamped to the month's actual last day).
function getMonthlyDateStr(year, month1, recurrenceValue) {
  const lastDay = new Date(year, month1, 0).getDate() // day 0 of next month = last day of this month
  const day = recurrenceValue === 'last' ? lastDay : Math.min(Number(recurrenceValue), lastDay)
  return `${year}-${String(month1).padStart(2, '0')}-${String(day).padStart(2, '0')}`
}

// Returns all "YYYY-MM-DD" strings that a rule should have generated by todayStr.
function getScheduledDates(rule, todayStr) {
  const startStr = rule.startDate
  const dates = []

  if (rule.recurrenceType === 'monthly') {
    const [sy, sm] = startStr.split('-').map(Number)
    const [ty, tm] = todayStr.split('-').map(Number)
    let year = sy
    let month = sm
    while (year < ty || (year === ty && month <= tm)) {
      const dateStr = getMonthlyDateStr(year, month, rule.recurrenceValue)
      if (dateStr >= startStr && dateStr <= todayStr) dates.push(dateStr)
      month++
      if (month > 12) { month = 1; year++ }
    }
  } else if (rule.recurrenceType === 'weekly') {
    const targetDay = WEEKDAY_INDEX[rule.recurrenceValue]
    const start = parseLocalDate(startStr)
    const today = parseLocalDate(todayStr)
    const current = new Date(start)
    // Advance to first occurrence of the target weekday on or after startDate.
    while (current.getDay() !== targetDay) current.setDate(current.getDate() + 1)
    while (current <= today) {
      const dateStr = localDateString(current)
      if (dateStr >= startStr && dateStr <= todayStr) dates.push(dateStr)
      current.setDate(current.getDate() + 7)
    }
  }

  return dates
}

// Compares existing expenses against all rules and returns newly-needed expense objects.
// Caller is responsible for persisting and merging these into state.
export function syncRecurringExpenses(rules, existingExpenses) {
  const todayStr = localDateString(new Date())

  // Build duplicate-prevention set from already-generated expenses.
  const generatedKeys = new Set()
  for (const exp of existingExpenses) {
    if (exp.recurringRuleId) {
      generatedKeys.add(`${exp.recurringRuleId}::${exp.date.slice(0, 10)}`)
    }
  }

  const newExpenses = []
  const generatedAt = new Date().toISOString()

  for (const rule of rules) {
    if (!rule.active) continue
    for (const dateStr of getScheduledDates(rule, todayStr)) {
      const key = `${rule.id}::${dateStr}`
      if (!generatedKeys.has(key)) {
        newExpenses.push({
          id: crypto.randomUUID(),
          amount: rule.amount,
          categoryId: rule.categoryId,
          note: rule.note,
          // Date stored as UTC midnight string — same convention as AddExpenseModal.
          date: new Date(dateStr).toISOString(),
          recurringRuleId: rule.id,
          generatedAt,
        })
        generatedKeys.add(key)
      }
    }
  }

  return newExpenses
}

export function recurrenceLabel(rule) {
  if (rule.recurrenceType === 'monthly') {
    if (rule.recurrenceValue === 'last') return 'Every month • Last day'
    return `Every month • ${ordinal(Number(rule.recurrenceValue))}`
  }
  return `Every week • ${WEEKDAY_LABELS[rule.recurrenceValue] ?? rule.recurrenceValue}`
}

function ordinal(n) {
  const s = ['th', 'st', 'nd', 'rd']
  const v = n % 100
  return n + (s[(v - 20) % 10] || s[v] || s[0])
}

// Default recurrence value when creating a new rule or switching recurrence type.
export function defaultRecurrenceValue(type) {
  if (type === 'monthly') return String(new Date().getDate())
  return ['sun', 'mon', 'tue', 'wed', 'thu', 'fri', 'sat'][new Date().getDay()]
}
